// Dados históricos da eleição 2022 por candidato.
// Para adicionar outro candidato: window.votosHistoricos['chave'] = { "CIDADE": votos, ... }
window.votosHistoricos = window.votosHistoricos || {};
window.votosHistoricos['celia'] = {
  "ANGRA DOS REIS": 31363, "APERIBE": 5, "ARARUAMA": 32, "AREAL": 5, "ARMACAO DOS BUZIOS": 8, "ARRAIAL DO CABO": 22,
  "BARRA DO PIRAI": 104, "BARRA MANSA": 1013, "BELFORD ROXO": 68, "BOM JARDIM": 2, "BOM JESUS DO ITABAPOANA": 23,
  "CABO FRIO": 177, "CACHOEIRAS DE MACACU": 9, "CAMBUCI": 144, "CAMPOS DOS GOYTACAZES": 1350, "CANTAGALO": 11,
  "CARAPEBUS": 7, "CARDOSO MOREIRA": 7, "CARMO": 5, "CASIMIRO DE ABREU": 9, "COMENDADOR LEVY GASPARIAN": 9,
  "CONCEICAO DE MACABU": 5, "CORDEIRO": 10, "DUAS BARRAS": 3, "DUQUE DE CAXIAS": 245, "ENGENHEIRO PAULO DE FRONTIN": 13,
  "GUAPIMIRIM": 19, "IGUABA GRANDE": 3, "ITABORAI": 39, "ITAGUAI": 180, "ITALVA": 51, "ITAOCARA": 63, "ITAPERUNA": 455,
  "ITATIAIA": 39, "JAPERI": 465, "LAJE DO MURIAE": 55, "MACAE": 334, "MACUCO": 2, "MAGE": 53, "MANGARATIBA": 322,
  "MARICA": 55, "MENDES": 29, "MESQUITA": 28, "MIGUEL PEREIRA": 58, "MIRACEMA": 965, "NATIVIDADE": 16, "NILOPOLIS": 42,
  "NITEROI": 648, "NOVA FRIBURGO": 26, "NOVA IGUACU": 920, "PARACAMBI": 46, "PARAIBA DO SUL": 239, "PARATY": 1069,
  "PATY DO ALFERES": 21, "PETROPOLIS": 56, "PINHEIRAL": 28, "PIRAI": 56, "PORCIUNCULA": 2, "PORTO REAL": 9, "QUATIS": 76,
  "QUEIMADOS": 210, "QUISSAMA": 16, "RESENDE": 61, "RIO BONITO": 12, "RIO CLARO": 1309, "RIO DAS FLORES": 25,
  "RIO DAS OSTRAS": 51, "RIO DE JANEIRO": 3312, "SANTA MARIA MADALENA": 0, "SANTO ANTONIO DE PADUA": 261,
  "SAO FIDELIS": 520, "SAO FRANCISCO DE ITABAPOANA": 64, "SAO GONCALO": 213, "SAO JOAO DA BARRA": 69,
  "SAO JOAO DE MERITI": 221, "SAO JOSE DE UBA": 11, "SAO JOSE DO VALE DO RIO PRETO": 10, "SAO PEDRO DA ALDEIA": 46,
  "SAO SEBASTIAO DO ALTO": 1, "SAPUCAIA": 10, "SAQUAREMA": 14, "SEROPEDICA": 112, "SILVA JARDIM": 5, "SUMIDOURO": 3,
  "TANGUA": 0, "TERESOPOLIS": 331, "TRES RIOS": 89, "VALENCA": 73, "VARRE-SAI": 0, "VASSOURAS": 733, "VOLTA REDONDA": 780
};